version: "3"

tasks:
  dev:
    cmds:
      - docker compose -f docker-compose.test.yml up -d
  stop:
    cmds:
      - docker compose -f docker-compose.test.yml stop
  down:
    cmds:
      - docker compose -f docker-compose.test.yml down
  logs:
    cmds:
      - docker compose -f docker-compose.test.yml logs
